spring:
  #datasource
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #jpa
  jpa:
    #hibernate
    hibernate:
      ddl-auto: create
    # properties
    properties:
      hibernate:
        format_sql: true
#logging
logging:
  level:
    org.hibernate.SQL: debug

# p6spy logging
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true